=== astojmir/PFMFind/FSindex/src/ShortFrags/data/setup_config/PFMFix.dtd
<!-- Root element -->
<!ELEMENT PFMF_index_setup (Database, Index_dir?, Dataset*)>

<!ELEMENT Database EMPTY>
<!ATTLIST Database
	driver CDATA #REQUIRED
	db CDATA #REQUIRED
	user CDATA #IMPLIED
	password CDATA #IMPLIED
	host CDATA #IMPLIED
	port CDATA #IMPLIED
>


<!ELEMENT Index_dir (#PCDATA)>

<!ELEMENT Dataset (Index*)>
<!ATTLIST Dataset
        name CDATA #REQUIRED
	schema CDATA #IMPLIED
	namespace CDATA #IMPLIED
	max_residues CDATA #IMPLIED
>

<!ELEMENT Index (Partition*)>
<!ATTLIST Index
        length CDATA #REQUIRED
>

<!ELEMENT Partition (#PCDATA)>

=== astojmir/PFMFind/examples/setup_config/ixsetup_sample01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PFMF_index_setup SYSTEM "PFMFix.dtd">
<PFMF_index_setup>
  <Database driver="psycopg" host="130.195.61.31" port="5432" user="aleksander" password="sasa" db="PFMFind"/>
  <Index_dir>/home/aleksander/data/uniprot-3.5/FSindex</Index_dir>
  <Dataset name="sprot" schema="PFMFind02" namespace="SwissProt" max_residues="80000000">
    <Index length="10">
      <Partition>STAN#ILVM#KRDEQ#WFYH#GPC</Partition>
    </Index>
    <Index length="12">
      <Partition>STAN#ILVM#KRDEQ#WFYHGPC</Partition>
    </Index>
  </Dataset>
</PFMF_index_setup>
