=== astojmir/PFMFind/FSindex/src/ShortFrags/data/setup_config/PFMFdb.dtd
<!-- Root element -->
<!ELEMENT PFMF_db_setup (Database, Schema?, Sql_dir?, Sql_scripts?, Taxonomy?, Uniprot_file*,Uniref_file*, InterPro_file*)>

<!ELEMENT Database EMPTY>
<!ATTLIST Database
	driver CDATA #REQUIRED
	db CDATA #REQUIRED
	user CDATA #IMPLIED
	password CDATA #IMPLIED
	host CDATA #IMPLIED
	port CDATA #IMPLIED
>

<!ELEMENT Schema EMPTY>
<!ATTLIST Schema
	name CDATA #REQUIRED
	create CDATA #IMPLIED
>

<!ELEMENT Sql_dir (#PCDATA)>

<!ELEMENT Sql_scripts EMPTY>
<!ATTLIST Sql_scripts
	sql_start CDATA #IMPLIED
	sql_end CDATA #IMPLIED
>

<!ELEMENT Taxonomy (Taxon_dir, Script_dir?)>
<!ATTLIST Taxonomy
	copy CDATA #IMPLIED
>

<!ELEMENT Taxon_dir (#PCDATA)>

<!ELEMENT Uniprot_file (#PCDATA)>
<!ATTLIST Uniprot_file
	namespace CDATA #REQUIRED
	sql_start CDATA #IMPLIED
	sql_end CDATA #IMPLIED
>

<!ELEMENT Uniref_file (#PCDATA)>
<!ATTLIST Uniref_file
	namespace CDATA #REQUIRED
	sql_start CDATA #IMPLIED
	sql_end CDATA #IMPLIED
>

<!ELEMENT InterPro_file (#PCDATA)>
<!ATTLIST InterPro_file
	namespace CDATA #REQUIRED
	sql_start CDATA #IMPLIED
	sql_end CDATA #IMPLIED
>

=== astojmir/PFMFind/FSindex/src/examples/setup_config/dbsetup_sample01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PFMF_db_setup SYSTEM "PFMFdb.dtd">
<PFMF_db_setup>
  <Database driver="psycopg" user="aleksander" db="PFMFind"/>
  <Schema name="PFMFind02" create="1"/>
  <Sql_dir>/home/aleksander/FSindex/src/pfmfind/data/sql-schema</Sql_dir>
  <Sql_scripts sql_start="biosqldb-pg-nocnstr.sql" sql_end="biosqldb-pg-cnstr.sql"/>
  <Taxonomy copy="1">
    <Taxon_dir>/home/aleksander/data/taxon_tables</Taxon_dir>
  </Taxonomy>
  <Uniprot_file namespace="SwissProt">/home/aleksander/data/uniprot-3.5/flatfiles/uniprot_sprot.dat</Uniprot_file>
  <Uniref_file namespace="SwissProt">/home/aleksander/data/uniprot-3.5/uniref/uniref50/uniref50.xml</Uniref_file>
  <InterPro_file namespace="SwissProt">/home/aleksander/data/uniprot-3.5/InterPro/Rel10.0-26042005/protein2interpro.dat</InterPro_file>
</PFMF_db_setup>
